### PR TITLE
Add .NET Core build tools workload package

### PR DESCRIPTION
**Pull request by nbalakin**

### CODE REVIEW

**Comment by jberezanski** [comment]
Thanks! I've given it a try and it works fine in basic scenarios. There are some problems with installing it over existing Build Tools installations (#7, #26), but those are known issues affecting all other VS 2017 packages and will be handled separately (eventually, I hope).

Do you know which Visual Studio version did this workload appear first in? (I believe it was not part of RTM, i.e. 15.0.)

**Comment by nbalakin** [comment]
If I've not mistaken 15.3 is was the first.
I'll check.

**Comment by jzinn** [comment]
I could use this.

**Comment by jberezanski** [comment]
OK, a change of plans.
I originally intended to wait with releasing this until I finish developing mechanisms to reliably update existing Visual Studio installations, but it's taking a lot of time (due to several quirks and flaws in the VS installer) and there is still work to be done there.
However, I suppose a package working in some scenarios is better than no package at all, so I'll release it now as-is. There will be no dependency on Visual Studio version (because the update mechanisms are not in place yet), but hopefully 15.3 has been available long enough (since August 2017) that most folks have it or a later version already.

**Comment by jberezanski** [comment]
I have merged it manually via an intermediate branch. It is now available for testing as prerelease:
````
cinst visualstudio2017-workload-netcorebuildtools --pre
````
I'll release it as an official version in a couple of days, if no problems appear.

**Comment by jberezanski** [comment]
https://chocolatey.org/packages/visualstudio2017-workload-netcorebuildtools

**Comment by jzinn** [comment]
It works fine from the command line.

**Comment by jzinn** [comment]
This is not a Chocolatey issue, but do you happen to know how to use pre-release Chocolatey packages when using Chef?

## What I am doing

I need the NuGet component that is part of the NetCoreBuildTools workload.  I'm currently installing the component this way:

```
chocolatey_package 'visualstudio2017buildtools' do
  options '--package-parameters "--add Microsoft.VisualStudio.Component.NuGet.BuildTools"'
end
```

I would like to simplify that to the following:
```
chocolatey_package 'visualstudio2017buildtools'
chocolatey_package 'visualstudio2017-workload-netcorebuildtools'
```

## Chef error
For my current recipe, I have
```
chocolatey_package 'visualstudio2017buildtools'
chocolatey_package 'visualstudio2017-workload-netcorebuildtools' do
	options '--pre'
	version '1.0.0-rc1'
end
```

but I am getting this error:
```
* chocolatey_package[visualstudio2017-workload-netcorebuildtools] action install
  * No candidate version available for visualstudio2017-workload-netcorebuildtools
  ================================================================================
  Error executing action `install` on resource 'chocolatey_package[visualstudio2017-workload-netcorebuildtools]'
  ================================================================================
       
  Chef::Exceptions::Package
  -------------------------
  No candidate version available for visualstudio2017-workload-netcorebuildtools
       
  Resource Declaration:
  ---------------------
  # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/xxxxxxx/recipes/windows.rb
       
   29: chocolatey_package 'visualstudio2017-workload-netcorebuildtools' do
   30: 	options '--pre'
   31: 	version '1.0.0-rc1'
   32: end
       
  Compiled Resource:
  ------------------
  # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/xxxxxxx/recipes/windows.rb:29:in `from_file'
       
  chocolatey_package("visualstudio2017-workload-netcorebuildtools") do
    package_name ["visualstudio2017-workload-netcorebuildtools"]
    action [:install]
    default_guard_interpreter :default
    declared_type :chocolatey_package
    cookbook_name "xxxxxxx"
    recipe_name "windows"
    options "--pre"
    version ["1.0.0-rc1"]
  end
       
  System Info:
  ------------
  chef_version=13.8.0
  platform=windows
  platform_version=10.0.10240
  ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
  program_name=C:/opscode/chef/bin/chef-client
  executable=C:/opscode/chef/bin/chef-client
```

**Comment by jberezanski** [comment]
Unfortunately, I have never used Chef. Perhaps @mwrock could help?

**Comment by jzinn** [comment]
Might want to add a note here: https://github.com/jberezanski/ChocolateyPackages/blob/22abdbd25435ac6cc3cdc9c7baa7f727f7ef6316/visualstudio2017buildtools/visualstudio2017buildtools.nuspec#L27-L32

**Comment by jberezanski** [comment]
Good point, thanks.

**Comment by jberezanski** [comment]
Merged via an intermediate branch and published:

https://chocolatey.org/packages/visualstudio2017-workload-netcorebuildtools/1.0.0

Thanks!

**Comment by jzinn** [comment]
I guess after publishing it still needs a moderators approval.  Yesterday it didn't work, but today, after approval, it is.  Thank you.

**Pull request closed without merging**
