### PR TITLE
Add support for powershell 7

### PR DESCRIPTION
**Pull request by tapika**
Add support for powershell 7 / swupd fork

### CODE REVIEW

**Comment by jberezanski** [comment]
What is the story behind this change? Right now, Chocolatey uses Windows PowerShell and I'm not aware of any specific plans or deadlines for switching to PowerShell Core.

**Comment by tapika** [comment]
My own fork https://github.com/tapika/swupd supports powershell v7 and I'm continuing to improve the system.

**Comment by tapika** [comment]
I have tested my changes also with choco, so should be backwards compatible.

**Comment by tapika** [comment]
Any progress ? This is at least blocking my work currently - wanted to start to upgrade choco / gui choco packages.

**Comment by tapika** [comment]
When I started testing - I've noticed that `Get-CimInstance` works out of box in `choco` - then googled a little bit, and it looks like this command was present even in powershell v2. So if-else variation is not needed - can just use newer version.

Updated version and changelog.

Do you do package publishing ?

**Comment by jberezanski** [comment]
No, PS 2.0 definitely does not have the CIM cmdlets. They were added as one of the major features of PS 3.0 ([official introduction](https://devblogs.microsoft.com/powershell/introduction-to-cim-cmdlets/)).
A quick test on Win7 confirms this:
```powershell
PS C:\> cmd /c ver

Microsoft Windows [Version 6.1.7601]
PS C:\> $PSVersionTable

Name                           Value
----                           -----
CLRVersion                     2.0.50727.5420
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1


PS C:\> Get-Command Get-CimInstance
Get-Command : The term 'Get-CimInstance' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:12
+ Get-Command <<<<  Get-CimInstance
    + CategoryInfo          : ObjectNotFound: (Get-CimInstance:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

PS C:\> cinst -y KB2454826
Chocolatey v1.1.0
Installing the following packages:
KB2454826
By installing, you accept licenses for the packages.
Progress: Downloading KB2454826 1.0.4... 100%

KB2454826 v1.0.4 [Approved]
kb2454826 package files install completed. Performing other installation steps.
ERROR: The term 'Get-CimInstance' is not recognized as the name of a cmdlet, function, script file, or operable program.
 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
The install of kb2454826 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\KB2454826\Tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - kb2454826 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\KB2454826\Tools\ChocolateyInstall.ps1'.
 See log for details.

```

So the command existence test is required.

One other thing: commit titles in this repo follow the pattern `<package>: <change>`, please adjust accordingly.

> Do you do package publishing ?

Yes, once the PR is ready I will merge it and publish the updated package.

**Comment by tapika** [comment]
Ok, most probably I have upgraded powershell on my windows 7, that's why have `CimCmdlets` as built-in in powershell.
Had to manually remove `C:\Windows\System32\WindowsPowerShell\v1.0\Modules\CimCmdlets` folder to test `choco`.

Hopefully now works ?

**Comment by jberezanski** [comment]
Yes, everything seems to be in order now.

**Comment by jberezanski** [comment]
I've published the updated extension. Thank you for your contribution!

**Comment by tapika** [comment]
Thanks. Waiting for 1.0.5 to be published, need to wait probably.

**Comment by jberezanski** [comment]
https://community.chocolatey.org/packages/chocolatey-windowsupdate.extension/1.0.5 - awaiting moderation. Might take longer than usual due to [an ongoing issue with the virus scanner](https://status.chocolatey.org/issues/2022-10-13-package-scanner-service-is-taking-longer-than-expected/).

**Pull request merged**
