### PR TITLE
Adding Visual Studio Component Functions

### PR DESCRIPTION
**Pull request by chrisrpatterson**
Adding functions to manage individual components to the chocolatey-visualstudio.extension package

### CODE REVIEW

**Comment by jberezanski** [comment]
Thanks!
As this is a new feature, not a bugfix, the [second version component will be incremented](http://semver.org/) (1.5.0). I'll deal with it.
I'm also working on another feature myself, so I'll probably wait with publishing 1.5.0 until I'm done (a couple of days).

**Comment by jberezanski** [comment]
I have merged this into the `visualstudio2017enterprise` branch. You can check out a prerelease build of the package here: https://www.myget.org/feed/jberezanski-chocolateypackages-dev/package/nuget/chocolatey-visualstudio.extension/1.5.0

**Comment by chrisrpatterson** [comment]
Awesome thanks, I will close this one out.

**Comment by chrisrpatterson** [comment]
@jberezanski any idea when you will get this updated to the official chocolatey feed?

**Comment by jberezanski** [comment]
Ah, thanks for reminding me. I've just pushed it.

**Comment by chrisrpatterson** [comment]
Awesome, thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
[HxS - 16299 - 16.0.8700.4019]

________________________________

**Pull request closed without merging**
